language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key: 57b76cb1-8d3a-4f55-994d-2f7766cf46cd
    secure: aQWYV+7y8Mu8RNn6q1IM2A6oyOwe1leh8zzP6T210Ysjg9iHTjOg8rl5Cw2Kxloc7uHin04MMiGfB9LU9oO6Eq37g2vDa5A1pOmxAIQaFfhtDILGjPXvxcdSqRNL62w1O650UjaxKLHIeDKbSUtMcVJL2GdJdcYob1oOD8fuq2e52ua2lXM4KE3xZfsnBrDD3XUfCMH8Zrm7+2nVBRgWeAK3Pm8QMRJz6Er7AzFlk74NtQdkg2VISiusEXl0eSNfyvJPbL9o8knkQ3GLXvZwwW8r8ECLxGX6pGzhCYUAIPJ1W21s8bEB7oC23GAwXfF8XZAYbIXDPnKqI0ku9KFjXnkbVBQLA8z3WM/sRAtaE42geYR0XG3ybvTGjnFe+aC+koH+GRAs0jeYZAuu2zBxZh8X3/FH2fBGzbvlQkPkZJoTzrbyB5Om5hUdbcs/14+bTjOpWmIBrBsEzaIiyMT11uBzS9QMHU3JFze9gjihqPdgrj1thZ9sLOQuwGgPpSj/8SxnEAczQxpaxjQzyVUwPi8lOGxFdZgkJfxoGsvOgelaTpH/KgE6mg9A6GRU5Is7SWUav1iGvu57QJXgBL7uBm/VrR3btFxcquDquLSzytD1fq6Q6Q7jjJJS4IES2tepUJhrhTErGAGCvBX7oT9rW4yx5oWzUMai0r0Itx/B4cg=
  app: mindful-eater-client
  on:
    repo: vmsimone/mindful-eater-client
