language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key: 57b76cb1-8d3a-4f55-994d-2f7766cf46cd
  app: mindful-eater-client
  on:
    repo: vmsimone/mindful-eater-client
